### ISSUE TITLE
cache store module

### ISSUE THREAD

**Issue by LAYAIraq** [LAYAIraq/LAYA-Iraq-Frontend#80]
In GitLab by @maufcons on Oct 22, 2021, 10:35

create a caching store to avoid redundant queries to backend

## tasks
- [ ] add cache module to store
- [x] create methods for user names
- [ ] create methods for course names
- [x] create user name getter in backend
- [ ] replace showUserName() in flag-answer.vue with new methods
- [ ] replace notification cache with new methods
