### ISSUE TITLE
Bugs & Feedback Staging 2021

### ISSUE THREAD

**Issue by LAYAIraq** [LAYAIraq/LAYA-Iraq-Frontend#87]
In GitLab by @maufcons on Nov 11, 2021, 14:56

List of Bugs that are in the current version (master branch as of Nov. 11, 2021):

- [x] register, login views accessible as logged-in user <#95>
- [x] change password only works at second request <#102>
- [x] content warning only work at second load of course list <#97>
- [x] changed content only is shown at page reload <#97>
- [x] content warning is false (shows warnings where not applicable, doesn't show warnings where it should) <#101>
- [x] no mails are sent <#94>
- [ ] flag icons obscure interactive parts (radio buttons, check boxes) <#106>
- [x] root view text somewhat false <#104>
- [x] cache timeout <#99>
- [x] reduce login cache timeout <#100>
- [x] redirect login from validation link doesn't work <#102>
- [x] reset password email is not sent <#103>
- [x] fix categories in drag&drop <#109>

Code Style:
- [x] fix linting errors after merging all bug fixes <#107>

Optimization: 
- [x] split build code into smaller parts <#88>
- [x] remove (or strip from build) console.log statements <#93>
